import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderLg from "./components/HeaderLg";
import HeaderSm from "./components/HeaderSm";
import Footer from "./components/FooterLg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden lg:block">
        <HeaderLg/>
        </div>
        <div className="block lg:hidden">
        <HeaderSm/>
        </div>
       
        {children}</body>
        <Footer/>
    </html>
  );
}
